/// Flutter icons Entypo
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Entypo
///      fonts:
///       - asset: fonts/Entypo.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class Entypo {
  Entypo._();

  static const _kFontFam = 'Entypo';
  static const String? _kFontPkg = null;

  static const IconData up_circled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circled = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
